apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
  selector:
    component: redis
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    component: redis
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
      - name: redis
        image: ndslabs/biocaddie-redis
        env:
          - name: MASTER 
            value: "true"
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /root/biocaddie/
          name: src
        - mountPath: /data
          name: data
      volumes:
      - name: src
        hostPath:
          path: /var/glfs/global/biocaddie/
      - name: data
        hostPath:
          path: /var/glfs/global/data/
