apiVersion: batch/v1
kind: Job
metadata:
  name: {{ name }}
spec:
  parallelism: 2
  template:
    metadata:
      name: {{ name }}
    spec:
      containers:
      - name: redis-worker
        image: ndslabs/redis-worker
        imagePullPolicy: IfNotPresent
        env:
        - name: REDIS_SERVICE_QUEUE
          value: "{{ name }}"
        volumeMounts:
        - mountPath: /queries
          name: queries
        - mountPath: /output
          name: output
        - mountPath: /data
          name: input
      volumes:
      - name: queries
        hostPath:
          path: /home/ubuntu/biocaddie/queries
      - name: output
        hostPath:
          path: /home/ubuntu/biocaddie/output
      - name: input
        hostPath:
          path: /data
      restartPolicy: Never
